"""create players table

Revision ID: 46d8d4bcaa8d
Revises: d0d4cd2df81f
Create Date: 2026-07-19 00:27:59.287947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46d8d4bcaa8d'
down_revision: Union[str, Sequence[str], None] = 'd0d4cd2df81f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odds',
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('bet_type_id', sa.Integer(), nullable=False),
    sa.Column('updated_at_api', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bet_type_id'], ['bet_types.id'], ),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'bookmaker_id', 'bet_type_id', name='uq_odds_fixture_bookmaker_bettype')
    )
    op.create_index(op.f('ix_odds_bet_type_id'), 'odds', ['bet_type_id'], unique=False)
    op.create_index(op.f('ix_odds_bookmaker_id'), 'odds', ['bookmaker_id'], unique=False)
    op.create_index(op.f('ix_odds_fixture_id'), 'odds', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_odds_id'), 'odds', ['id'], unique=False)
    op.create_table('odd_values',
    sa.Column('odd_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['odd_id'], ['odds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odd_values_id'), 'odd_values', ['id'], unique=False)
    op.create_index(op.f('ix_odd_values_odd_id'), 'odd_values', ['odd_id'], unique=False)
    op.add_column('bet_markets', sa.Column('api_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('bet_markets_name_key'), 'bet_markets', type_='unique')
    op.create_index(op.f('ix_bet_markets_api_id'), 'bet_markets', ['api_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bet_markets_api_id'), table_name='bet_markets')
    op.create_unique_constraint(op.f('bet_markets_name_key'), 'bet_markets', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('bet_markets', 'api_id')
    op.drop_index(op.f('ix_odd_values_odd_id'), table_name='odd_values')
    op.drop_index(op.f('ix_odd_values_id'), table_name='odd_values')
    op.drop_table('odd_values')
    op.drop_index(op.f('ix_odds_id'), table_name='odds')
    op.drop_index(op.f('ix_odds_fixture_id'), table_name='odds')
    op.drop_index(op.f('ix_odds_bookmaker_id'), table_name='odds')
    op.drop_index(op.f('ix_odds_bet_type_id'), table_name='odds')
    op.drop_table('odds')
    # ### end Alembic commands ###
