"""create player tables

Revision ID: c0ad61a2f4e2
Revises: 46d8d4bcaa8d
Create Date: 2026-07-19 02:01:28.129377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ad61a2f4e2'
down_revision: Union[str, Sequence[str], None] = '46d8d4bcaa8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.String(length=20), nullable=True),
    sa.Column('birth_place', sa.String(length=100), nullable=True),
    sa.Column('birth_country', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('height', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.String(length=20), nullable=True),
    sa.Column('injured', sa.Boolean(), nullable=False),
    sa.Column('photo', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_api_id'), 'players', ['api_id'], unique=True)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_table('player_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('appearances', sa.Integer(), nullable=True),
    sa.Column('lineups', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('captain', sa.Boolean(), nullable=False),
    sa.Column('sub_in', sa.Integer(), nullable=True),
    sa.Column('sub_out', sa.Integer(), nullable=True),
    sa.Column('bench', sa.Integer(), nullable=True),
    sa.Column('shots_total', sa.Integer(), nullable=True),
    sa.Column('shots_on', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('passes_total', sa.Integer(), nullable=True),
    sa.Column('passes_key', sa.Integer(), nullable=True),
    sa.Column('passes_accuracy', sa.Integer(), nullable=True),
    sa.Column('tackles_total', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('duels_total', sa.Integer(), nullable=True),
    sa.Column('duels_won', sa.Integer(), nullable=True),
    sa.Column('dribbles_attempts', sa.Integer(), nullable=True),
    sa.Column('dribbles_success', sa.Integer(), nullable=True),
    sa.Column('dribbled_past', sa.Integer(), nullable=True),
    sa.Column('fouls_drawn', sa.Integer(), nullable=True),
    sa.Column('fouls_committed', sa.Integer(), nullable=True),
    sa.Column('yellow', sa.Integer(), nullable=True),
    sa.Column('yellow_red', sa.Integer(), nullable=True),
    sa.Column('red', sa.Integer(), nullable=True),
    sa.Column('penalty_won', sa.Integer(), nullable=True),
    sa.Column('penalty_committed', sa.Integer(), nullable=True),
    sa.Column('penalty_scored', sa.Integer(), nullable=True),
    sa.Column('penalty_missed', sa.Integer(), nullable=True),
    sa.Column('penalty_saved', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'team_id', 'league_id', 'season', name='uq_player_statistics')
    )
    op.create_index(op.f('ix_player_statistics_id'), 'player_statistics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_statistics_id'), table_name='player_statistics')
    op.drop_table('player_statistics')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_players_api_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
