"""add api_id to bookmakers

Revision ID: cfc7b7a7cb59
Revises: 0a4e6261b136
Create Date: 2026-07-18 00:06:00.846691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc7b7a7cb59'
down_revision: Union[str, Sequence[str], None] = '0a4e6261b136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('potential_return', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('bets', sa.Column('payout', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('bets', sa.Column('profit', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('bookmakers', sa.Column('api_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_bookmakers_api_id'), 'bookmakers', ['api_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmakers_api_id'), table_name='bookmakers')
    op.drop_column('bookmakers', 'api_id')
    op.drop_column('bets', 'profit')
    op.drop_column('bets', 'payout')
    op.drop_column('bets', 'potential_return')
    # ### end Alembic commands ###
