"""remove unique from bet_types name

Revision ID: d0d4cd2df81f
Revises: dbb519fb0cbb
Create Date: 2026-07-18 19:46:02.661865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d4cd2df81f'
down_revision: Union[str, Sequence[str], None] = 'dbb519fb0cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bet_types_name_key'), 'bet_types', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('bet_types_name_key'), 'bet_types', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
