"""add api_id to bet_types

Revision ID: dbb519fb0cbb
Revises: cfc7b7a7cb59
Create Date: 2026-07-18 19:35:34.326957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbb519fb0cbb'
down_revision: Union[str, Sequence[str], None] = 'cfc7b7a7cb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_types', sa.Column('api_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_bet_types_api_id'), 'bet_types', ['api_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bet_types_api_id'), table_name='bet_types')
    op.drop_column('bet_types', 'api_id')
    # ### end Alembic commands ###
